#warmup period 155 1 min candles
candles = 5

up=70
down=30
dev=0.9

[fstochrsi]
#for RSI
interval = 14
#for Stoch
stoch = 9
#for %K
k = 3
#for %D
d = 3

[bbands]
TimePeriod = 21
NbDevUp = 2
NbDevDn = 2

[thresholds]
low = 40
high = 60
persistence = 4

