interval = 14
sellpercent = 0.98
sellpersistence = 3

s_dn = 0.1
s_up = 0.1


[bbands]
TimePeriod = 20
NbDevUp = 2
NbDevDn = 2

[thresholds]
low = 20
high = 80
persistence = 4
s_low = 30
s_high = 70
s_persistence = 3
